"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

try:
    from celery.schedules import crontab
except ImportError:  # pragma: no cover
    crontab = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load `backend/.env` (copy from `.env.example`). Not required if you set env vars elsewhere.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:  # pragma: no cover
    pass

# Celery (usage event ingestion queue). Use Redis in production; eager = no broker for local dev.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
# Default eager=True so ingest works without Redis; set CELERY_TASK_ALWAYS_EAGER=0 + run Celery worker for real queuing.
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "true").lower() in (
    "1",
    "true",
    "yes",
)
CELERY_TASK_EAGER_PROPAGATES = True

# Periodic ETL / analytics (run: celery -A backend beat -l info)
CELERY_BEAT_SCHEDULE = (
    {
        "usage-daily-rollup": {
            "task": "smartagile.tasks.run_usage_daily_rollup",
            "schedule": crontab(hour=3, minute=5),
        },
        # Scheduling agent: recurring usage digests for opted-in users.
        "usage-digest-daily": {
            "task": "smartagile.tasks.send_scheduled_usage_digests",
            "schedule": crontab(hour=7, minute=0),
            "args": ("daily",),
        },
        "usage-digest-weekly": {
            "task": "smartagile.tasks.send_scheduled_usage_digests",
            "schedule": crontab(hour=7, minute=30, day_of_week=1),  # Monday
            "args": ("weekly",),
        },
        # Proactive nudges: scan for at-risk sprints (hourly) and personal work/focus (daily).
        "nudges-sprint-risks": {
            "task": "smartagile.tasks.scan_sprint_risks_task",
            "schedule": crontab(minute=0),  # top of every hour
        },
        "nudges-personal": {
            "task": "smartagile.tasks.scan_personal_nudges_task",
            "schedule": crontab(hour=8, minute=15),  # once a day, morning
        },
    }
    if crontab is not None
    else {}
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r3h2&j%kg3#+e5ucokumy&z01uhza8dkv*67q^vbu*k$flf@lu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'smartagile',
    'assistant',
    'tasks',
    'sprints',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'smartagile.authentication.LenientJWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'


WSGI_APPLICATION = 'backend.wsgi.application'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
 # Not recommended for production
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
] 
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartagile_database',
        'USER':'postgres',
        'PASSWORD':'1350',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Local timezone for day-boundary logic. Events are still stored in UTC (USE_TZ=True);
# this only controls how dates are computed/grouped (TruncDate, localdate, localtime),
# so "Today" on the dashboard/app-details matches the user's local calendar day.
# Override per deployment via the TIME_ZONE env var if needed.
TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Outgoing mail (password reset OTP, etc.). Set EMAIL_HOST_USER + EMAIL_HOST_PASSWORD in `backend/.env`.
# Default: Python 3.12+ compatible (Django 3.2’s stock SMTP uses removed starttls(keyfile=...)).
# Override with e.g. django.core.mail.backends.console.EmailBackend for local tests.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "smartagile.smtp_backend.Py312CompatEmailBackend")
EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "tarunutla1234@gmail.com").strip()
# Gmail app passwords are 16 characters; users often paste with spaces — SMTP needs them removed.
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip().replace(" ", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "webmaster@localhost")

# Console logging (see runserver terminal). Override with DJANGO_LOG_LEVEL=DEBUG|INFO|WARNING
DJANGO_LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()
if DJANGO_LOG_LEVEL not in ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"):
    DJANGO_LOG_LEVEL = "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # SMTP / mail backend (connection errors show here when level is DEBUG)
        "django.core.mail": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "smartagile": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# --- SmartAgile assistant (LangGraph + LLM) ---
# LLM_PROVIDER: "auto" (default) = Groq first, then OpenAI if Groq is missing or errors;
#   "groq" = only Groq; "openai" = only OpenAI.
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "auto").strip().lower()
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "").strip() or None
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "").strip()
GROQ_BASE_URL = os.environ.get("GROQ_BASE_URL", "https://api.groq.com/openai/v1").strip()
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
# Embeddings for semantic memory (OpenAI-compatible).
# Note: Groq is used for chat in auto mode, but embeddings typically use OpenAI.
EMBEDDINGS_PROVIDER = os.environ.get("EMBEDDINGS_PROVIDER", "auto").strip().lower()
OPENAI_EMBEDDING_MODEL = os.environ.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small").strip()
GROQ_EMBEDDING_MODEL = os.environ.get("GROQ_EMBEDDING_MODEL", "").strip()
# When True, use a small LLM call for intent (if a chat model is available).
ASSISTANT_LLM_CLASSIFY = os.environ.get("ASSISTANT_LLM_CLASSIFY", "0").lower() in ("1", "true", "yes")
# When True, use LLM to phrase the final answer from loaded JSON (if a chat model is available).
ASSISTANT_LLM_SYNTHESIZE = os.environ.get("ASSISTANT_LLM_SYNTHESIZE", "1").lower() in ("1", "true", "yes")
# Prior chat turns loaded for the assistant (user+assistant lines). ~24 ≈ last 6 exchanges; cap prevents huge prompts.
try:
    ASSISTANT_SESSION_MESSAGE_LIMIT = max(
        4, min(int(os.environ.get("ASSISTANT_SESSION_MESSAGE_LIMIT", "24")), 48)
    )
except ValueError:
    ASSISTANT_SESSION_MESSAGE_LIMIT = 24
try:
    ASSISTANT_SESSION_MESSAGE_MAX = max(8, min(int(os.environ.get("ASSISTANT_SESSION_MESSAGE_MAX", "48")), 80))
except ValueError:
    ASSISTANT_SESSION_MESSAGE_MAX = 48