from django.urls import path

from .views import (
    AssistantScopeView,
    BacklogView,
    GroupListView,
    GroupSummaryView,
    OrgSummaryView,
    ProjectMembersView,
    SprintBoardView,
    SprintBurndownView,
    SprintCompleteView,
    SprintDetailView,
    SprintEffortView,
    SprintItemEffortView,
    SprintListCreateView,
    SprintReportView,
    SprintStartView,
    TimerActiveView,
    TimerStartView,
    TimerStopView,
    WorkItemCommentListCreateView,
    WorkItemDetailDataView,
    WorkItemDetailView,
    WorkItemListCreateView,
)

urlpatterns = [
    path("sprints/", SprintListCreateView.as_view(), name="sprint-list-create"),
    path("sprints/<int:pk>/", SprintDetailView.as_view(), name="sprint-detail"),
    path("sprints/<int:pk>/start/", SprintStartView.as_view(), name="sprint-start"),
    path("sprints/<int:pk>/complete/", SprintCompleteView.as_view(), name="sprint-complete"),
    path("sprints/<int:pk>/board/", SprintBoardView.as_view(), name="sprint-board"),
    path("sprints/<int:pk>/burndown/", SprintBurndownView.as_view(), name="sprint-burndown"),
    path("sprints/<int:pk>/report/", SprintReportView.as_view(), name="sprint-report"),
    path("sprints/<int:pk>/effort/", SprintEffortView.as_view(), name="sprint-effort"),
    path("sprints/<int:pk>/item-effort/", SprintItemEffortView.as_view(), name="sprint-item-effort"),
    path("timer/active/", TimerActiveView.as_view(), name="timer-active"),
    path("timer/start/", TimerStartView.as_view(), name="timer-start"),
    path("timer/stop/", TimerStopView.as_view(), name="timer-stop"),
    path("backlog/", BacklogView.as_view(), name="backlog"),
    path("groups/", GroupListView.as_view(), name="group-list"),
    path("groups/<int:pk>/summary/", GroupSummaryView.as_view(), name="group-summary"),
    path("org/summary/", OrgSummaryView.as_view(), name="org-summary"),
    path("assistant/scope/", AssistantScopeView.as_view(), name="assistant-scope"),
    path("projects/<int:pk>/members/", ProjectMembersView.as_view(), name="project-members"),
    path("items/", WorkItemListCreateView.as_view(), name="workitem-create"),
    path("items/<int:pk>/", WorkItemDetailView.as_view(), name="workitem-detail"),
    path("items/<int:pk>/detail/", WorkItemDetailDataView.as_view(), name="workitem-detail-data"),
    path(
        "items/<int:pk>/comments/",
        WorkItemCommentListCreateView.as_view(),
        name="workitem-comments",
    ),
]
