# Generated by Django 5.1 on 2024-09-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0009_delete_task'),
        ('tasks', '0007_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartagile.signupdata'),
        ),
    ]
