# Generated by Django 3.2.25 on 2026-03-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
