# Generated by Django 3.2.25 on 2026-04-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0011_auto_20260330_1855'),
        ('tasks', '0011_project_org_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='smartagile.signupdata'),
        ),
    ]
