# Generated by Django 3.2.25 on 2026-06-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
        ('tasks', '0013_alter_user_fks_to_accounts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('chore', 'Chore'), ('spike', 'Spike')], default='task', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='rank',
            field=models.FloatField(default=0, help_text='Manual ordering within backlog / board column.'),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sprints.sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
