# Generated by Django 3.2.25 on 2026-06-29 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_auto_20260630_0001'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='taskworksession',
            index=models.Index(fields=['user', 'started_at'], name='sprints_tas_user_id_b7e6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskworksession',
            index=models.Index(fields=['user', 'ended_at'], name='sprints_tas_user_id_e95f7e_idx'),
        ),
    ]
