# Generated by Django 3.2.25 on 2026-06-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20260630_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprints', '0002_auto_20260630_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workitemcomment',
            index=models.Index(fields=['task', 'created_at'], name='sprints_wor_task_id_b8c149_idx'),
        ),
    ]
