# Generated by Django 5.1 on 2024-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0008_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
