# Generated by Django 3.2.25 on 2026-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0010_auth_session_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authsessionevent',
            name='smartagile_authevent_user_created',
        ),
        migrations.AddIndex(
            model_name='authsessionevent',
            index=models.Index(fields=['user', 'created_at'], name='smartagile__user_id_dbf2e5_idx'),
        ),
    ]
