# Generated by Django 3.2.25 on 2026-04-25 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartagile', '0018_assistant_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('habit', 'Habit'), ('preference', 'Preference'), ('constraint', 'Constraint'), ('project_context', 'Project context'), ('other', 'Other')], default='other', max_length=32)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='assistant_chat', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-last_used_at', '-created_at', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='assistantchatmessage',
            name='smartagile__session_0c4b1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistantchatsession',
            name='smartagile__user_id_6f0c8a_idx',
        ),
        migrations.AddIndex(
            model_name='assistantchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='smartagile__session_9dd02e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantchatsession',
            index=models.Index(fields=['user', '-updated_at'], name='smartagile__user_id_3e5680_idx'),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', '-created_at'], name='smartagile__user_id_f4f6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', '-last_used_at'], name='smartagile__user_id_6ddf49_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', 'type', '-created_at'], name='smartagile__user_id_785698_idx'),
        ),
    ]
