# Generated by Django 3.2.25 on 2026-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartagile', '0019_auto_20260425_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
