# Generated by Django 3.2.25 on 2026-06-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20260630_0001'),
        ('smartagile', '0020_auto_20260629_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='tasks.task'),
        ),
    ]
