# Generated by Django 3.2.25 on 2026-06-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20260630_0057'),
        ('tasks', '0014_auto_20260630_0001'),
        ('smartagile', '0023_auto_20260630_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('work_item', 'Work item'), ('comment', 'Comment'), ('sprint_goal', 'Sprint goal')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='tasks.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_chunks', to='sprints.sprint')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='tasks.task')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['project', 'source_type'], name='smartagile__project_0b81d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='knowledge_source_uniq'),
        ),
    ]
